### ISSUE TITLE
Change wording of label

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/oeh-arcmap-addin#2]
Change wording of label from 'OEH Layers' to 'OEH Core Layers' - the label appears: 1) when you hover the mouse over the smiley face, and 2) at top of page when it opens, and 3) in the banner when you install – see below.  

![oeh add in](https://user-images.githubusercontent.com/4453449/31358391-28089760-ad91-11e7-864d-d51f074cb092.jpg)

**Comment by byezy** [comment]
AddCoreLayers...   so don't you want tit to be "Core Layers"  (NO OEH?)

**Comment by TomWaterat** [comment]
I think just "Add Core Layers" would be fine.. Apparently EPA uses it to???

**Comment by TomWaterat** [comment]
done
