### ISSUE TITLE
Increase size of available layers list box

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/oeh-arcmap-addin#3]
Can the Available Layers list box window be made larger to include more of the list? It's only a minor issue, If this is a default ESRI parameter that is hard to change don't worry.

![oeh add in2](https://user-images.githubusercontent.com/4453449/31358936-66e4b58e-ad93-11e7-875b-fbb5b54930b1.jpg)

**Comment by byezy** [comment]
Can't be done. Size is set by ArcGIS. Perhaps go back to the original plane and have 3 x tables, one  for each category???

**Comment by TomWaterat** [comment]
That's not a bad idea. Would it be easier if it used three input CSVs?

**Comment by byezy** [comment]
no diff really, not much anyway probably easier for thos guys to use one don't know

**Comment by TomWaterat** [comment]
Leave it at one.. can change later if needed.
