### ISSUE TITLE
Location of the 'layers.csv' file

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/oeh-arcmap-addin#5]
The add-in currently uses the layers.csv input file from P:\Corporate\Tools\Software\CoreLayers.  Apparently BIS Spatial are phasing out P:\Corporate (and as a result are making it very difficult for anyone updated files on P:\Corporate).  Anni has asked if it would be possible to look for the 'layers.csv' file on P:\Region\Other\Tools\CoreLayers?  The best solution would be to have an input box for the user to select the input file to use.

**Comment by byezy** [comment]
Hi Tom, input box is not a good solution. 

Pin down a new location and name for the file please. 

Can be fixed in seconds.

**Comment by TomWaterat** [comment]
New path = P:\Region\Other\Tools\CoreLayers\Layers.csv
